### ISSUE TITLE
Banding

### ISSUE THREAD

**Issue by JustinBWatson** [CalebBabin/opl.io#1]
I seem to be noticing some "banding". Might wanna check this out. Kinda game breaking if you ask me.

https://images-ext-2.discordapp.net/external/2udRR2Yca0ZENDM-s1O-_mUPicZPNe1I4eKfKPfDMWc/https/i.gyazo.com/1a5168ccdf1b34cca18a8eb8e1ddbc30.png

- THE GEEKEN

**Comment by CalebBabin** [comment]
NO

**Comment by CalebBabin** [comment]
Also it's fixed now.

thanks for NOTHING
